# Auto-label PRs based on changed paths (modules/*)
# Labels are defined in .github/labels.yml and applied here.

"module: animate":
  - changed-files:
      - any-glob-to-any-file: modules/animate/**
  - head-branch: [".*animate.*"]
"module: arduino_serial":
  - changed-files:
      - any-glob-to-any-file: modules/arduino_serial/**
  - head-branch: [".*arduino[_-]?serial.*"]
"module: calibration":
  - changed-files:
      - any-glob-to-any-file: modules/calibration/**
  - head-branch: [".*calibration.*"]
"module: autonomy":
  - changed-files:
      - any-glob-to-any-file: modules/autonomy/**
  - head-branch: [".*autonomy.*"]
"module: camera":
  - changed-files:
      - any-glob-to-any-file: modules/camera/**
  - head-branch: [".*camera.*"]
"module: config_center":
  - changed-files:
      - any-glob-to-any-file: modules/config_center/**
  - head-branch: [".*config[_-]?center.*"]
"module: diagnostics":
  - changed-files:
      - any-glob-to-any-file: modules/diagnostics/**
  - head-branch: [".*diagnostics.*"]
"module: gateway":
  - changed-files:
      - any-glob-to-any-file: modules/gateway/**
  - head-branch: [".*gateway.*"]
"module: hardware":
  - changed-files:
      - any-glob-to-any-file: modules/hardware/**
  - head-branch: [".*hardware.*"]
"module: interactions":
  - changed-files:
      - any-glob-to-any-file: modules/interactions/**
  - head-branch: [".*interactions.*"]
"module: logwrapper":
  - changed-files:
      - any-glob-to-any-file: modules/logwrapper/**
  - head-branch: [".*logwrapper.*"]
"module: mutagen":
  - changed-files:
      - any-glob-to-any-file: modules/mutagen/**
  - head-branch: [".*mutagen.*"]
"module: neopixel":
  - changed-files:
      - any-glob-to-any-file: modules/neopixel/**
  - head-branch: [".*neopixel.*"]
"module: notifier":
  - changed-files:
      - any-glob-to-any-file: modules/notifier/**
  - head-branch: [".*notifier.*"]
"module: ollama":
  - changed-files:
      - any-glob-to-any-file: modules/ollama/**
  - head-branch: [".*ollama.*"]
"module: ota":
  - changed-files:
      - any-glob-to-any-file: modules/ota/**
  - head-branch: [".*ota.*"]
"module: piservo":
  - changed-files:
      - any-glob-to-any-file: modules/piservo/**
  - head-branch: [".*piservo.*"]
"module: scheduler":
  - changed-files:
      - any-glob-to-any-file: modules/scheduler/**
  - head-branch: [".*scheduler.*"]
"module: speak":
  - changed-files:
      - any-glob-to-any-file: modules/speak/**
  - head-branch: [".*speak.*"]
"module: speech":
  - changed-files:
      - any-glob-to-any-file: modules/speech/**
  - head-branch: [".*speech.*"]
"module: state_manager":
  - changed-files:
      - any-glob-to-any-file: modules/state_manager/**
  - head-branch: [".*state[_-]?manager.*"]
"module: telemetry":
  - changed-files:
      - any-glob-to-any-file: modules/telemetry/**
  - head-branch: [".*telemetry.*"]
"module: vision_bridge":
  - changed-files:
      - any-glob-to-any-file: modules/vision_bridge/**
  - head-branch: [".*vision[_-]?bridge.*"]
"module: wiki_rag":
  - changed-files:
      - any-glob-to-any-file: modules/wiki_rag/**
  - head-branch: [".*wiki[_-]?rag.*"]

# Label PRs targeting dev branch
"target: dev":
  - base-branch: ["^dev$"]

# Label feature PRs by branch name prefix (e.g., feat-...)
"type: feature":
  - head-branch: ["^feat[-/].*", "^feature[-/].*"]
