# Repository label definitions (to be synced by workflow)
# Name and color must be stable; description is optional.

- name: "module: animate"
  color: "1f77b4"
  description: "Changes in modules/animate"
- name: "module: arduino_serial"
  color: "ff7f0e"
  description: "Changes in modules/arduino_serial"
- name: "module: calibration"
  color: "2ca02c"
  description: "Changes in modules/calibration"
- name: "module: camera"
  color: "d62728"
  description: "Changes in modules/camera"
- name: "module: config_center"
  color: "9467bd"
  description: "Changes in modules/config_center"
- name: "module: diagnostics"
  color: "8c564b"
  description: "Changes in modules/diagnostics"
- name: "module: gateway"
  color: "e377c2"
  description: "Changes in modules/gateway"
- name: "module: hardware"
  color: "7f7f7f"
  description: "Changes in modules/hardware"
- name: "module: interactions"
  color: "bcbd22"
  description: "Changes in modules/interactions"
- name: "module: logwrapper"
  color: "17becf"
  description: "Changes in modules/logwrapper"
- name: "module: mutagen"
  color: "1a9850"
  description: "Changes in modules/mutagen"
- name: "module: neopixel"
  color: "d73027"
  description: "Changes in modules/neopixel"
- name: "module: notifier"
  color: "a6cee3"
  description: "Changes in modules/notifier"
- name: "module: ollama"
  color: "b2df8a"
  description: "Changes in modules/ollama"
- name: "module: ota"
  color: "fb9a99"
  description: "Changes in modules/ota"
- name: "module: piservo"
  color: "fdbf6f"
  description: "Changes in modules/piservo"
- name: "module: scheduler"
  color: "cab2d6"
  description: "Changes in modules/scheduler"
- name: "module: speak"
  color: "ffff99"
  description: "Changes in modules/speak"
- name: "module: speech"
  color: "1b9e77"
  description: "Changes in modules/speech"
- name: "module: state_manager"
  color: "d95f02"
  description: "Changes in modules/state_manager"
- name: "module: telemetry"
  color: "7570b3"
  description: "Changes in modules/telemetry"
- name: "module: vision_bridge"
  color: "e7298a"
  description: "Changes in modules/vision_bridge"
- name: "module: wiki_rag"
  color: "66a61e"
  description: "Changes in modules/wiki_rag"

# target/type helper labels
- name: "target: dev"
  color: "0366d6"
  description: "Pull request targets the dev branch"
- name: "type: feature"
  color: "0e8a16"
  description: "Feature branch (feat-*, feature-*)"

- name: "target: main"
  color: "f9d423"
  description: "Pull request targets the main branch"
